language: php

php:
  - 7.2
  - 7.3

before_script:
  - sudo apt-get install php php-xml php-gd php-mbstring php-curl
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit tests
